#!/usr/bin/env python3
"""Generate the shared farmer module from explicitly tagged teaching cells.

SP.ipynb is the authored source. Companion notebooks import the generated module;
no notebook executes another notebook or carries a separately edited model copy.
"""
import argparse
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / 'notebooks/4-dev/SP.ipynb'
OUTPUT = ROOT / 'notebooks/farmer.py'


def render():
    nb = json.loads(SOURCE.read_text())
    cells = [''.join(c['source']).rstrip() for c in nb['cells']
             if 'farmer-library' in c.get('metadata', {}).get('tags', [])]
    if not cells:
        raise ValueError('No farmer-library cells found')
    body = '\n\n\n'.join(cells) + '\n'
    compile(body, str(OUTPUT), 'exec')
    digest = hashlib.sha256(body.encode()).hexdigest()
    return ('# GENERATED by scripts/export_farmer_library.py; do not edit.\n'
            '# Source: notebooks/4-dev/SP.ipynb cells tagged farmer-library\n'
            f'# Source-cell SHA256: {digest}\n\n' + body)


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    expected = render()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text() != expected:
            raise SystemExit('STALE: run scripts/export_farmer_library.py')
        print('Farmer module matches all tagged source cells.')
    else:
        OUTPUT.write_text(expected)
        print(f'Wrote {OUTPUT.relative_to(ROOT)}')
